### ISSUE TITLE
Printervenlig

### ISSUE THREAD

**Issue by HeleneNB** [HBreddam/hbreddam.github.io#7]
Det kunne være sejt, hvis der var en knap til en printervenlig udgave af opskriften, hvor der ikke er al "hyggeteksten" med.

**Comment by HBreddam** [comment]
https://stackoverflow.com/questions/242182/how-can-i-pop-up-a-print-dialog-box-using-javascript

**Comment by HBreddam** [comment]
https://stackoverflow.com/questions/12997123/print-specific-part-of-webpage

**Comment by HBreddam** [comment]
Ide: lav en knap i opskrift include'en der trigger javascriptet fra anden kommentar.

**Comment by HBreddam** [comment]
[Text](#link){: .btn .btn--info}

**Comment by HBreddam** [comment]
@HeleneNB Printvenlig version1 er klar:
http://breddamsmad.dk/Poelsehorn-med-poolish/

**Comment by HBreddam** [comment]
Version 2:
Krav:
Formatering
Afvent billedet loader

To do:
- Lær Jquery
Implementer det her: https://stackoverflow.com/questions/34455981/print-a-div-containing-dynamic-image
